// Random splash texts shown next to the Arcade title.
// Easy to edit — add or remove lines freely. One string per item.
export const SPLASH_TEXTS: string[] = [
  "Now with 100% more vibes!",
  "Don't tell your teacher!",
  "Press ALT+F4 for a free skin!",
  "Made with love and questionable code",
  "Definitely not procrastinating",
  "Skill issue? Try the next game.",
  "Powered by snacks",
  "It's giving arcade",
  "Touch grass... later",
  "Speedrun your homework first",
  "Brain rot incoming",
  "Better than school WiFi",
  "Built different",
  "Certified bangers only",
  "Pro tip: panic button works",
  "Achievement unlocked: opened the site",
  "1v1 me bro",
  "Big W energy",
  "Sigma grindset arcade",
  "100% Irish-approved",
  "Bo selecta!",
  "No cap, this slaps",
  "Vibes only",
  "Don't get caught!",
  "Free shipping on dopamine",
  "Lag-free since 2026",
  "Goated with the sauce",
  "Try the new ones!",
  "Pin your favorites!",
  "Tell a friend!",
];
